[workspace]
members = ["common", "daemon", "trojan"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
android_logger = "0.15"
async-trait = "0.1"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
futures-util = "0.3"  # Todo: remove when https://github.com/hannobraun/inotify-rs/commit/0056f98f381f9de330126663b6bcf4969112e9f1 published
inotify = "0.11"
log = "0.4"
memfd = "0.6"
memmap2 = "0.9"
nix = { version = "0.31" }
once_map = "0.4"
paste = "1.0"
procfs = "0.18"
r3solvr = { git = "https://github.com/Mufanc/r3solvr" }
rsbinder = { version = "0.6", features = ["android_13", "android_14", "android_16"] }
rsbinder-aidl = "0.6"
scopeguard = "1.2"
syscalls = "0.8"
tokio = { version = "1", features = ["rt", "macros"] }
uds = "0.4"
wisp = { git = "https://github.com/Mufanc/wisp" }

[profile.release]
lto = true
opt-level = "s"
strip = true
split-debuginfo = "packed"
debug = "line-tables-only"

[profile.release.package.daemon]
codegen-units = 1

[profile.release.package.trojan]
codegen-units = 1
