[package]
name = "daemon"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mist"
path = "src/main.rs"

[dependencies]
android_logger = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
futures-util = { workspace = true }
mist_common = { path = "../common" }
env_logger = { workspace = true }
inotify = { workspace = true }
log = { workspace = true }
memfd = { workspace = true }
nix = { workspace = true, features = ["ptrace", "signal", "socket", "uio"] }
once_map = { workspace = true }
procfs = { workspace = true }
r3solvr = { workspace = true }
rsbinder = { workspace = true }
scopeguard = { workspace = true }
syscalls = { workspace = true }
tokio = { workspace = true }
uds = { workspace = true }

[build-dependencies]
rsbinder-aidl = { workspace = true }
